#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(shinyWidgets)  # better Shiny UI widgets
library(shinythemes) # pretty shiny interface
library(tidyverse) 
library(tidymodels) # for fitting decision tree
library(markdown) # for incorporating credit file

cat_vars <- c("race", "sex", "degree", "relig", "zodiac", "res16", "party_id3", "padeg", "madeg", "dwelling",
              "dwelown", "wrkslf", "wrkgovt", "marital", "reg16", "parborn", "vote12", "pres12", "famgen",
              "vetyears", "voted_16")
cont_vars = c("age", "educ", "sibs", "wordsum", "agekdbrn", "childs")

vars_default = c("age", "party_id3", "res16")

makeTree = function(model_vars, cost_complexity = .01, metric, data) {
  f = paste("voted_16 ~ ", paste(model_vars, collapse = " + "))
  tree = decision_tree(mode = "classification",
                       cost_complexity = cost_complexity) %>%
    set_engine("rpart",
               parms = list(split = metric)) %>%
    fit(as.formula(f),
        data = data)
  
  return(tree)
}

plotTree = function(tree){
  plot = rpart.plot::rpart.plot(tree$fit, type = 4, extra=101, under = TRUE, 
                                box.palette = "BuOr",
                                roundint = FALSE)
  return(plot)
}

textTree = function(tree){
  table = data.frame(rpart.plot::rpart.rules(
    tree$fit, 
    roundint=FALSE, 
    clip.facs=TRUE, 
    cover = TRUE,
    style = "tall")) %>% 
    as_tibble()
  cols_to_squish = colnames(table)[2:(ncol(table)-1)]
  table = table %>% 
    unite("Rules", all_of(cols_to_squish)) %>%
    mutate(p_voted = 1-as.numeric(voted_16)) %>%
    select(-voted_16) %>%
    select(`P(Voted)` = p_voted, Rules, `% of Data` = `X..cover`)
  return(as_tibble(table))
}

useTree = function(tree, data) {
  # Takes a tree generated by rpart and a filename (string) as input and
  # then predicts the labels of the data in that file using the tree. It
  # returns a dataframe with two bool (0,1) columns: prediction and truth.
  
  prediction = predict(tree, data, type = "class")
  results = as.data.frame(prediction)
  results$truth = data$voted_16
  
  return(results)
}


calcScores = function(results) {
  # Takes a results dataframe as input and then calculates scores for
  # accuracy, true negative rate, and true positive rate. It returns a
  # list of formatted strings detailing these results.
  
  results = table(results)
  # calculate the scores on which we'll judge our model to 2 decimal places
  accuracy = round(100 * (results[1] + results[4]) / sum(results), 2)
  true_neg = round(100 * results[1] / sum(results[1, ]), 2)
  true_pos = round(100 * results[4] / sum(results[2, ]), 2)
  
  # the collapse argument removes the spacing which would otherwise be there
  return(list(
    paste(c("Overall Accuracy: ",   accuracy, "%"), collapse = "")#,
    #paste(c("True Positive Rate: ", true_pos, "%"), collapse = ""),
    #paste(c("True Negative Rate: ", true_neg, "%"), collapse = "")
  ))
}


ui <- fluidPage(theme = shinytheme("flatly"),

    # Application title
    titlePanel("General Social Survey Classification Trees"),

    # Sidebar with a slider input for number of bins 
    sidebarLayout(
        sidebarPanel(
          h4("Variables to include"),
          helpText(
            "Choose as many as you would like"
          ),
          pickerInput(
            inputId = "gss_vars",
            label = NULL,  # label given in outer code
            choices = c(cat_vars, cont_vars),
            selected = vars_default,
            options = list(`actions-box` = TRUE),
            multiple = TRUE
          ),
          h4("Cost/Complexity Parameter"),
          helpText(
            "Smaller values lead to a more complicated tree"
          ),
          sliderInput(
            inputId = "cost_comp",
            label = NULL,  # label given in outer code
            min = 1e-5,       # two is the smallest that could be split
            max = .1,      # chosen to not make the models too wild
            value = .01      # defaults to not having an artifical minimum
          ),
          h4("Metric for Splitting"),
          radioGroupButtons(
            inputId = "metric",
            label = NULL,
            choiceNames = c("Gini Index", 
                        "Information Gain"),
            choiceValues = c("gini",
                             "information"),
            justified = TRUE
          ),
          actionButton(
            inputId = "createModel",
            label = "Create Model",
            class = "btn-primary"  # makes it blue!
          ),
          helpText(
            "Pressing this blue button creates a decision tree model for",
            "the original data, based on the variables and complexity parameter",
            "you've selected. Use this while you're still developing your model.",
            "If you change the selected features, press it again to regenerate the model.",
            ""
          ),
          actionButton(
            inputId = "testModel",
            label = "Fit to test data",
            class = "btn-danger"  # makes it blue!
          ),
          helpText(
            "Happy with your model? Excellent! Press the above red",
            "button to run it on the test data. Only use this once you",
            "believe you have a reasonable model and are ready to assess it.",
            "See the results on the Test Data tab."
          )
        ),

        # Show a plot of the generated distribution

          mainPanel(
            tabsetPanel(
              tabPanel("Tree Output", plotOutput("tree_plot"), 
                       textOutput("training_scores")),
              tabPanel("Decision Rules", tableOutput("tree_text")),
              tabPanel("Variable Descriptions", tableOutput("var_descriptions")),
              tabPanel("Test Data",textOutput("test_scores")),
              tabPanel("Credits",htmltools::includeMarkdown("credits.md"))
            )
          )

)
)


server <- function(input, output, session) {
   variables = read_csv("data/variable-descriptions.csv")
  
  
    train_data = read_csv("data/training-data.csv") %>%
      mutate(
        # Make all categorical variables factors and relabel nicely
        across(all_of(cat_vars), forcats::as_factor),
        across(all_of(cont_vars), as.numeric)
      )
    test_data = read_csv("data/test-data.csv") %>%
      mutate(
        # Make all categorical variables factors and relabel nicely
        across(all_of(cat_vars), forcats::as_factor),
        across(all_of(cont_vars), as.numeric)
      )
    
    tree = eventReactive(input$createModel,
      valueExpr = makeTree(
        model_vars = c(input$gss_vars), 
        cost_complexity = input$cost_comp,
        metric = input$metric,
        data = train_data
      )
    )
    
    # regenerate training results every time createModel is pressed
    training_results = eventReactive(input$createModel,
      valueExpr = useTree(tree(), train_data)
    )
    
    test_results = eventReactive(input$testModel,
                                     valueExpr = useTree(tree(), test_data)
    )
    
    pressed = eventReactive(input$createModel,
                            {input$gss_vars})
    
    plot_results = eventReactive(input$createModel,
                                 valueExpr = plotTree(tree())
    )
    
    text_results = eventReactive(input$createModel,
                                 valueExpr = textTree(tree())
    )
    
    output$tree_plot = renderPlot(
      plot_results()
    )
    
    output$tree_text = renderTable({
      text_results()
    })
    
    output$var_descriptions <- renderTable({
      variables
    })
    
    output$training_scores = renderText(
      paste(calcScores(training_results()), collapse = "\n")
    )
    
    output$test_scores = renderText(
      paste(calcScores(test_results()), collapse = "\n")
    )
    
    
    output$selectedVars <- renderText(pressed())
    
}

# Run the application 
shinyApp(ui = ui, server = server)
